### ISSUE TITLE
login to opengts

### ISSUE THREAD

**Issue by daveherbert6** [Andre0991/opengts-install-ubuntu#4]
I have setup opengts using your tutorial.
The problem I have is login in.
I created the username and password with:
bin/admin.sh Account-account=sysadmin -pass=w408801e -create

However there are 3 fields to enter on the login page:

Account:  
User:  
Password: 

I hope you can help

**Comment by Andre0991** [comment]
It's been a while since I last installed OpenGTS, but I think you can just leave `User` blank and then add users as you login with your account.

Checking the [official manual](http://opengts.sourceforge.net/OpenGTS_Config.pdf) may help too.

Hope that helps :)

**Comment by mehulkatara-zz** [comment]
enter your account and password
leave user blank
it will work ;-)

**Comment by Andre0991** [comment]
Thanks @mehulkatara.
